import os

with open("Sensors.h", "w") as file:
    file.write("// This file was generated by " + os.path.basename(__file__) + "\n\n")

    file.write("#ifndef SENSORS_H\n")
    file.write("#define SENSORS_H\n\n")

    file.write("#include \"definitions.h\"\n")
    file.write("#include \"Sensor/Sensor.h\"\n\n")

    file.write("Sensor sensors[] = {\n")

    for scl in range(8):
        for sda in range(8):
            file.write("    {\n")
            file.write("        .i2c =\n")
            file.write("        {\n")
            file.write("            .scl = SCL" + str(scl) + "_PIN,\n")
            file.write("            .sda = SDA" + str(sda) + "_PIN,\n")
            file.write("            .halfClockCycle = 1,\n")
            file.write("        }\n")
            file.write("    },\n")

    file.write("};\n\n")

    file.write("#endif\n")
