// This file was generated by generateSensors.py

#ifndef SENSORS_H
#define SENSORS_H

#include "definitions.h"
#include "Sensor/Sensor.h"

#define SENSORS_NUMBER_OF_SENSORS (64)

Sensor sensors[] = {
    {
        .i2c =
        {
            .scl = SCL0_PIN,
            .sda = SDA0_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL0_PIN,
            .sda = SDA1_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL0_PIN,
            .sda = SDA2_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL0_PIN,
            .sda = SDA3_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL0_PIN,
            .sda = SDA4_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL0_PIN,
            .sda = SDA5_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL0_PIN,
            .sda = SDA6_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL0_PIN,
            .sda = SDA7_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL1_PIN,
            .sda = SDA0_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL1_PIN,
            .sda = SDA1_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL1_PIN,
            .sda = SDA2_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL1_PIN,
            .sda = SDA3_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL1_PIN,
            .sda = SDA4_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL1_PIN,
            .sda = SDA5_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL1_PIN,
            .sda = SDA6_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL1_PIN,
            .sda = SDA7_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL2_PIN,
            .sda = SDA0_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL2_PIN,
            .sda = SDA1_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL2_PIN,
            .sda = SDA2_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL2_PIN,
            .sda = SDA3_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL2_PIN,
            .sda = SDA4_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL2_PIN,
            .sda = SDA5_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL2_PIN,
            .sda = SDA6_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL2_PIN,
            .sda = SDA7_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL3_PIN,
            .sda = SDA0_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL3_PIN,
            .sda = SDA1_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL3_PIN,
            .sda = SDA2_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL3_PIN,
            .sda = SDA3_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL3_PIN,
            .sda = SDA4_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL3_PIN,
            .sda = SDA5_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL3_PIN,
            .sda = SDA6_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL3_PIN,
            .sda = SDA7_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL4_PIN,
            .sda = SDA0_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL4_PIN,
            .sda = SDA1_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL4_PIN,
            .sda = SDA2_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL4_PIN,
            .sda = SDA3_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL4_PIN,
            .sda = SDA4_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL4_PIN,
            .sda = SDA5_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL4_PIN,
            .sda = SDA6_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL4_PIN,
            .sda = SDA7_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL5_PIN,
            .sda = SDA0_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL5_PIN,
            .sda = SDA1_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL5_PIN,
            .sda = SDA2_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL5_PIN,
            .sda = SDA3_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL5_PIN,
            .sda = SDA4_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL5_PIN,
            .sda = SDA5_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL5_PIN,
            .sda = SDA6_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL5_PIN,
            .sda = SDA7_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL6_PIN,
            .sda = SDA0_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL6_PIN,
            .sda = SDA1_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL6_PIN,
            .sda = SDA2_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL6_PIN,
            .sda = SDA3_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL6_PIN,
            .sda = SDA4_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL6_PIN,
            .sda = SDA5_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL6_PIN,
            .sda = SDA6_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL6_PIN,
            .sda = SDA7_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL7_PIN,
            .sda = SDA0_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL7_PIN,
            .sda = SDA1_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL7_PIN,
            .sda = SDA2_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL7_PIN,
            .sda = SDA3_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL7_PIN,
            .sda = SDA4_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL7_PIN,
            .sda = SDA5_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL7_PIN,
            .sda = SDA6_PIN,
            .halfClockCycle = 1,
        }
    },
    {
        .i2c =
        {
            .scl = SCL7_PIN,
            .sda = SDA7_PIN,
            .halfClockCycle = 1,
        }
    },
};

#endif
